function [sliedata, headers, veclabs, vecnums] = read_sliedatafile(fname, datafmt)
% Function to read in ASCII data files generated by sliealizer.
%  ** See: slie_writesliedatafile.m 
%
% Data may be numeric (i.e. landfast ice width) or text(datestrings)
% Format can be specified when called 
%
% USAGE
%          sliedata = read_sliedatafile(fname)
%          sliedata = read_sliedatafile(fname, datafmt)
%     [__, headers] = read_sliedatafile(__)
%     [__, veclabs] = read_sliedatafile(__)
%     [__, vecnums] = read_sliedatafile(__)
%
% INPUTS
%     fname : string specifying full path and filename for ASCII file
%             containing SLIE data 
%   datafmt : string specifying the data format to be read
%             e.g., "%f" for numeric data, or "s" for string data
%             Default: '%f'
%
% OUTPUT
%    sliedata : Nvecs-by-Nslies array of data read from file.
%               For numeric data, this will be an array of doubles
%               For text data this will be a cell array of strings
%     headers : Column headers containing either names of SLIEs or months
%     veclabs : Any coast vector labels read along the way
%     vecnums : Array of coast vecor indices
%
%
% Andy Mahoney - October 2023
%
%
% -----------------------------------------------------------------------


% Set a numeric data format if none specified
if ~exist('datafmt', 'var')
    datafmt = '%f';
end


% Open file for reading as text
infid = fopen(fname, 'r');

% Read header line with SLIE/month information
headline = fgetl(infid);
headsplit = regexp(headline, ',', 'split');
headers = strtrim(headsplit(3:end)');
Nhead = numel(headers);

% Generate format for textscan parsing of datalines
infmt = '%s %d';
for h=1:Nhead
    infmt = [infmt ' ' datafmt];
end

indata = textscan(infid, infmt, 'delimiter', ',');

% Extract vector labels and numeric indices 
% from first and second columns
veclabs = indata{1};
vecnums = indata{2};

% Treat rest of columns differently depending
% whether they are text or numeric data
if ~iscell(indata{3})
    sliedata = cell2mat(indata(3:end));
else
    Nv = numel(vecnums);
    sliedata = cell(Nv,Nhead);
    for s=1:Nhead
        sliedata(:,s) = indata{s+2};
    end
end


% Close input file
fclose(infid);

% Provide some feedback for user
disp(['Read data file: ' fname]);

end

